---
title: "Home"
editor: visual
---

## Personal Information

**Name:** Yumeng.Tian\
**E-mail address:** Yumeng.Tian21\@student.xjtlu.edu.cn\
**Contact number:** + 86 15850018060\

## Educational Background

XJTLU & University of Liverpool, UK\
**Major:**\
Mathematics and Applied Mathematics\
**Major courses:**\
Probability and statistics; Numerical analysis; PDE; ODE; Java; Dynamic modeling; Calculus; Linear algebra; Abstract algebra, etc\
**Scholarship:**\
·21-22 Academic Scholarship "University Academic Excellence Award"\
·22–23 Academic Scholarship "University Academic Achievement Award"\
·22-23 "Merit Student" at XJTLU\

## Workplace Experience

-   **New Oriental Educational & Technology Group** January 2024-March 2024\
    Quality Intelligence Department / Intern Head Teacher\
    ·Answer questions and correct homework according to the teaching content\
    ·Track and feedback students' phased learning effect\
    \
-   **Huatai United Securities** June 2023-September 2023\
    Investment Banking Business Line / Jiangsu Business Department / Jiangsu Group 2 / Intern\
    ·Participated in the "Xidian Xineng IPO" project, carried out enterprise inventory, bank statement verification, letter processing, manuscript update and sorting\
    ·Use Microsoft Excel to check and analyze the bank flow data of enterprises and individuals\
    ·The final issuer was successfully registered in November 2023\
    \
-   **XJTLU ILEAD** June 2022-September 2022\
    Introduction of Wisdom Training / Teaching Assistant\
    ·Prepare materials for lecturers and confirm training arrangements\
    ·Collect, analyze and report training data\
    ·Lead participating teachers to complete ice-breaking and campus visits\

## Project Experience

-   **PWC - "Battle 24H" Business Competition** March 2023\
    ·Provide a business case analysis including background, solution strategy, impact and other aspects through two-person cooperation\
    ·Mainly responsible for the preliminary overall framework and the solutions of this case analysis\

## School Experience

-   **Administrative Class League Branch Secretary** September 2022-Present\
    ·Responsible for the daily management and construction of the class, assist the monitor and DA to organize class activities\
    ·Complete the basic work, ensure the implementation of decision-making, and promote teaching\
    \
-   **XJTLU Student News Centre** March 2022-March 2023\
    Member of the Vision Department\
    ·Responsible for planning, shooting, post-processing, tweet beautification and pictures; master basic shooting, editing and tweet production skills\
    \
-   **“ALMA” International Volunteer Team** October 2021-October 2022\
    Minister of the Secretary Department\
    ·Responsible for financial management and activity material purchase; site negotiation and classroom platform reservation; record the daily activities of the community; assign work tasks for members\

## Personal Skills

-   **Computer skills:** Microsoft Office; Matlab; Latex\
-   **Language level:** English; Spanish
